// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class WorkerStats : MonoBehaviour
{

    public TextAsset file;

    void Start()
    {
        Load(file);
    }


    public class Row
    {
        public string Name;
        public string Morale;
        public string Loyalty;
    }

    List<Row> rowList = new List<Row>();
    bool isLoaded = false;

    public bool IsLoaded()
    {
        return isLoaded;
    }

    public List<Row> GetRowList()
    {
        return rowList;
    }

    public void Load(TextAsset csv)
    {
        rowList.Clear();
        string[][] grid = CsvParser2.Parse(csv.text);
        for (int i = 1; i < grid.Length; i++)
        {
            Row row = new Row();
            row.Name = grid[i][0];
            row.Morale = grid[i][1];
            row.Loyalty = grid[i][2];

            rowList.Add(row);
        }
        isLoaded = true;
    }

    public int NumRows()
    {
        return rowList.Count;
    }

    public Row GetAt(int i)
    {
        if (rowList.Count <= i)
            return null;
        return rowList[i];
    }

    public Row Find_Name(string find)
    {
        return rowList.Find(x => x.Name == find);
    }
    public List<Row> FindAll_Name(string find)
    {
        return rowList.FindAll(x => x.Name == find);
    }
    public Row Find_Morale(string find)
	{
		return rowList.Find(x => x.Morale == find);
	}
public List<Row> FindAll_Morale(string find)
	{
    return rowList.FindAll(x => x.Morale == find);
}
public Row Find_Loyalty(string find)
	{
    return rowList.Find(x => x.Loyalty == find);
}
public List<Row> FindAll_Loyalty(string find)
	{
    return rowList.FindAll(x => x.Loyalty == find);
}

}